apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-toy-car
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: toy-car
  template:
    metadata:
      labels:
        app: toy-car
    spec:
      containers:
      - name: toy-car
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
